version: "3.12"

services:
  db:
    image: timescale/timescaledb-ha:pg16
    platform: linux/amd64
    volumes:
      - /data/db:/var/lib/postgresql/data
      - /data/db_backups:/var/lib/postgresql/backups
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  cassandra:
    hostname: cassandra
    image: cassandra:latest

  elasticsearch:
    image: elasticsearch:7.8.1
    platform: linux/amd64
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_USER=${ELASTICSEARCH_USER}
      - ELASTICSEARCH_PASS=${ELASTICSEARCH_PASS}
    ports:
      - "9200:9200"

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py sync_cassandra &&
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ELASTICSEARCH_USER=${ELASTICSEARCH_USER}
      - ELASTICSEARCH_PASS=${ELASTICSEARCH_PASS}
      - MAIL=${MAIL}
      - MAIL_PASS=${MAIL_PASS}
    depends_on:
      - db
      - elasticsearch
      - redis
      - cassandra

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  celery:
    image: celery_api:latest
    working_dir: /code/
    build: .
    command: celery -A nartsozluk worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MAIL=${MAIL}
      - MAIL_PASS=${MAIL_PASS}
    depends_on:
      - rabbitmq
  celery-beat:
    working_dir: /code/
    build: .
    command: celery -A nartsozluk beat -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - rabbitmq
      - celery
